# This is a basic workflow to help you get started with Actions

name: CI-CD


on:
   push:
    branches: [ main ]

    workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}     
    - name: Docker Build and Push
      uses: docker/build-push-action@v2.8.0
      with:
        context: ./home/oswaldo/Documentos/K8S/DO/rotten-potatoes/src/
        file: ./src/Docker/File
        push: true
        tags: |
            oswaldogrimaldi/rotten-potatoes:latest
            oswaldogrimaldi/rotten-potatoes:${{ github.run_number }}
            
